# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration workflow

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10 (as server Dockerfile)
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f cli/requirements.txt ]; then pip install -e cli; fi
        if [ -f server/requirements.txt ]; then pip install -r server/requirements.txt; fi

    - name: Set server environment vars
      working-directory: ./server
      run: cp .env.example .env

    - name: Run migrations
      working-directory: ./server
      run: python manage.py migrate

    - name: Run django server in background
      working-directory: ./server
      run: python manage.py runserver &

    - name: Run integration tests
      working-directory: ./server
      run: pip install -r test-requirements.txt --user && python seed.py

    - name: Install Docker
      run: |
        sudo apt-get update -y
        sudo apt-get install \
        ca-certificates \
        curl \
        gnupg \
        lsb-release -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get install moby-engine moby-cli containerd.io

    - name: Run client integration tests
      working-directory: ./cli
      run: sh cli.sh
